### ISSUE TITLE
Cannot build on Android

### ISSUE THREAD

**Issue by XeonG** [yasirkula/UnityIngameDebugConsole#75]
Cannot build on Android 2023.1.A16..
```

Assets\Plugins\UnityIngameDebugConsole\Plugins\IngameDebugConsole\Scripts\DebugLogItem.cs(194,13): error CS1061: 'TMP_Text' does not contain a definition for 'SetTMPHorizontalOverflow' and no accessible extension method 'SetTMPHorizontalOverflow' accepting a first argument of type 'TMP_Text' could be found (are you missing a using directive or an assembly reference?)

Assets\Plugins\UnityIngameDebugConsole\Plugins\IngameDebugConsole\Scripts\DebugLogItem.cs(207,13): error CS1061: 'TMP_Text' does not contain a definition for 'SetTMPHorizontalOverflow' and no accessible extension method 'SetTMPHorizontalOverflow' accepting a first argument of type 'TMP_Text' could be found (are you missing a using directive or an assembly reference?)

Assets\Plugins\UnityIngameDebugConsole\Plugins\IngameDebugConsole\Scripts\DebugLogItem.cs(281,42): error CS1061: 'TMP_Text' does not contain a definition for 'GetTMPHorizontalOverflow' and no accessible extension method 'GetTMPHorizontalOverflow' accepting a first argument of type 'TMP_Text' could be found (are you missing a using directive or an assembly reference?)

Assets\Plugins\UnityIngameDebugConsole\Plugins\IngameDebugConsole\Scripts\DebugLogItem.cs(284,12): error CS1061: 'TMP_Text' does not contain a definition for 'SetTMPHorizontalOverflow' and no accessible extension method 'SetTMPHorizontalOverflow' accepting a first argument of type 'TMP_Text' could be found (are you missing a using directive or an assembly reference?)

Assets\Plugins\UnityIngameDebugConsole\Plugins\IngameDebugConsole\Scripts\DebugLogItem.cs(289,12): error CS1061: 'TMP_Text' does not contain a definition for 'SetTMPHorizontalOverflow' and no accessible extension method 'SetTMPHorizontalOverflow' accepting a first argument of type 'TMP_Text' could be found (are you missing a using directive or an assembly reference?)

```

**Comment by yasirkula** [comment]
Hi, I'm assuming that you've used TextToTextMeshPro plugin and a script must've been reverted to its original form after upgrading IngameDebugConsole. If you haven't modified IngameDebugConsole's source code, could you reinstall it from scratch and apply TextToTextMeshPro again?
